name: Areacars CI

on:
   push:
      branches: ["beta"]

jobs:
   build:
      runs-on: self-hosted

      defaults:
         run:
            working-directory: /var/www/areacars-admin

      strategy:
         matrix:
            node-version: [16.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
         - uses: actions/checkout@v3
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v3
           with:
              node-version: ${{ matrix.node-version }}

         - name: "Checkout to Beta branch"
           run: git checkout beta

         - name: "Pull Latest code"
           run: git pull

         - name: "Install Dependencies"
           run: yarn

         - name: "Build for production"
           run: yarn build
